# Generated by Django 4.2.4 on 2024-02-03 04:30

from django.db import migrations, models
import django.db.models.deletion
import justo_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0006_alter_clientes_fin_lic_alter_clientes_ini_lic_and_more'),
        ('localidades_app', '0001_initial'),
        ('terceros_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='celular1',
            field=models.CharField(help_text='El número de celular debe contener exactamente 10 dígitos numéricos.', max_length=10, null=True, validators=[justo_app.models.validate_numeric], verbose_name='Celular 1'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='celular2',
            field=models.CharField(max_length=10, null=True, verbose_name='Celular 2'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='cla_doc',
            field=models.CharField(choices=[('C', 'Cédula de Ciudadanía'), ('T', 'Tarjeta de Identidad'), ('N', 'Nit'), ('R', 'Registro Civil'), ('E', 'Cédula de Extranjería'), ('P', 'Pasaporte'), ('O', 'Otros')], max_length=1, verbose_name='Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_app.clientes', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='cod_ciu_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciu_exp', to='localidades_app.localidades', verbose_name='Ciudad Expedición Documento'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='cod_ciu_res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciu_res', to='localidades_app.localidades', verbose_name='Ciudad Residencia'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='cod_pos',
            field=models.CharField(max_length=8, null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='dig_ver',
            field=models.CharField(max_length=1, null=True, verbose_name='DV'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='direccion',
            field=models.CharField(max_length=80, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='doc_ide',
            field=models.CharField(max_length=12, verbose_name='Número Documento'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='fax',
            field=models.CharField(max_length=10, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='fec_act',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='fec_exp_ced',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Expedición Documento'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='nit_interno',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Nit Interno'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='nit_rap',
            field=models.CharField(max_length=12, null=True, verbose_name='Nit Rápido'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='observacion',
            field=models.CharField(max_length=255, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='per_pub_exp',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Persona Expuesta PEP'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='pri_ape',
            field=models.CharField(max_length=28, null=True, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='pri_nom',
            field=models.CharField(max_length=28, null=True, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='raz_soc',
            field=models.CharField(max_length=120, null=True, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='regimen',
            field=models.CharField(choices=[('48', 'Responsable'), ('49', 'No Responsable'), ('Comun', 'Común')], max_length=12, verbose_name='Tipo Régimen'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='seg_ape',
            field=models.CharField(max_length=28, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='seg_nom',
            field=models.CharField(max_length=28, null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tel_ofi',
            field=models.CharField(max_length=10, null=True, verbose_name='Teléfono Oficina'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tel_res',
            field=models.CharField(max_length=10, null=True, verbose_name='Teléfono Residencia'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tip_ter',
            field=models.CharField(choices=[('N', 'Persona Natural'), ('J', 'Persona Jurídica'), ('O', 'Otro')], max_length=12, verbose_name='Tipo Tercero'),
        ),
    ]
