# Generated by Django 4.2.4 on 2023-11-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociados',
            name='cargo_emp',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='ciu_res',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='ciu_tra',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='cod_ciiu',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='dir_emp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='estrato',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='med_con',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='negocio_nom',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='negocio_tel',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='nit_emp',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='nom_emp',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='ocupacion_cod',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pension_ent',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pension_ent_otr',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pep_cargo',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pep_fam_nom',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='profesion',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='sector_emp',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='tel_tra',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='tip_con',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='tip_sal',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='tip_viv',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='zona',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
