# Generated by Django 4.2.4 on 2023-10-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidades',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='localidades',
            name='cod_pos',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='localidades',
            name='departamento',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
