# Generated by Django 4.2.4 on 2024-01-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hecho_econo',
            name='id_ds',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
