# Generated by Django 4.2.4 on 2023-11-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0002_alter_asociados_cargo_emp_alter_asociados_ciu_res_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estados_fin',
            name='egr_des_nom',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
    ]
