# Generated by Django 4.2.4 on 2024-01-05 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0002_alter_hecho_econo_id_ds'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detalle_econo',
            unique_together=set(),
        ),
    ]
