# Generated by Django 5.0 on 2023-12-23 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0002_imp_con_cre_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DESTINO_CRE',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justo_app.clientes')),
            ],
            options={
                'db_table': 'destino_cre',
                'unique_together': {('cliente', 'codigo')},
            },
        ),
    ]
