# Generated by Django 4.2.4 on 2023-11-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0002_remove_localidades_ciudad_localidades_cod_pos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='regimen',
            field=models.CharField(choices=[('48', 'Responsable'), ('49', 'No Responsable'), ('Comun', 'Comun')], max_length=12),
        ),
    ]
