# Generated by Django 5.0 on 2023-12-23 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0003_destino_cre'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAT_DES_DIA_CRE',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('categoria', models.CharField(choices=[('A', 'Normal'), ('B', 'Apreciable'), ('C', 'En Peligro'), ('D', 'En Mora'), ('E', 'Irrecuperable'), ('F', 'Castigado')], max_length=1)),
                ('minimo_dias', models.IntegerField(null=True)),
                ('maximo_dias', models.IntegerField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justo_app.clientes')),
            ],
            options={
                'db_table': 'cat_des_dia_cre',
                'unique_together': {('cliente', 'codigo', 'categoria')},
            },
        ),
    ]
