# Generated by Django 4.2.4 on 2023-11-03 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0003_alter_terceros_regimen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='cod_ciu_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciu_exp', to='justo_app.localidades'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='cod_ciu_res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciu_res', to='justo_app.localidades'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='fec_exp_ced',
            field=models.DateField(null=True),
        ),
    ]
