# Generated by Django 4.2.4 on 2023-11-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0003_alter_estados_fin_egr_des_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estados_fin',
            name='act_otr',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
    ]
