# Generated by Django 4.2.4 on 2023-11-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0004_alter_terceros_cod_ciu_exp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='nombre',
            field=models.CharField(blank=True, max_length=68, null=True),
        ),
    ]
