# Generated by Django 5.0 on 2023-12-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0004_cat_des_dia_cre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imp_con_cre_int',
            name='kporcentaje',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
