# Generated by Django 4.2.4 on 2023-11-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0005_alter_estados_fin_act_tip_bien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estados_fin',
            name='escritura',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
