# Generated by Django 5.0 on 2023-12-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0005_alter_imp_con_cre_int_kporcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='imp_con_cre_int',
            name='orden_i',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
