# Generated by Django 4.2.4 on 2023-11-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0006_alter_estados_fin_escritura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estados_fin',
            name='pas_otr',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
    ]
