# Generated by Django 5.0 on 2023-12-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0006_imp_con_cre_int_orden_i'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imp_con_cre',
            old_name='kcta_pte',
            new_name='kcta_pte_cap',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre_int',
            name='cta_val',
        ),
        migrations.AddField(
            model_name='imp_con_cre',
            name='cta_val',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='imp_con_cre',
            name='kcta_pte_int',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
