# Generated by Django 4.2.4 on 2024-01-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0006_remove_creditos_val_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditos',
            name='cap_ini',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
