# Generated by Django 5.0 on 2023-12-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0007_rename_kcta_pte_imp_con_cre_kcta_pte_cap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imp_con_cre_int',
            name='orden_i',
        ),
        migrations.AddField(
            model_name='imp_con_cre',
            name='kcta_ingreso',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='imp_con_cre',
            name='orden_i',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
