# Generated by Django 5.0 on 2023-12-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0008_remove_imp_con_cre_int_orden_i_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imp_con_cre_int',
            name='cta_por_pag',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre_int',
            name='icta_pte',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre_int',
            name='icxca',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre_int',
            name='icxcb',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre_int',
            name='icxcc',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre_int',
            name='icxcd',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre_int',
            name='icxce',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre_int',
            name='icxcf',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre_int',
            name='orden_c',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre_int',
            name='orden_d',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre_int',
            name='orden_e',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre_int',
            name='orden_f',
        ),
    ]
