# Generated by Django 4.2.4 on 2023-11-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0008_alter_estados_fin_pas_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='estados_fin',
            name='ing_otr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
