# Generated by Django 5.0 on 2023-12-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0009_remove_imp_con_cre_int_cta_por_pag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imp_con_cre_int',
            name='cta_int',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imp_con_cre_int',
            name='cta_ord_int',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
