# Generated by Django 4.2.4 on 2024-01-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0009_detalle_prod_oficina'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='detalle_prod',
            index=models.Index(fields=['oficina'], name='detalle_pro_oficina_aca602_idx'),
        ),
    ]
