# Generated by Django 5.0 on 2023-12-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0010_imp_con_cre_int_cta_int_imp_con_cre_int_cta_ord_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imp_con_cre_int',
            name='cta_int',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='imp_con_cre_int',
            name='cta_ord_int',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
