# Generated by Django 4.2.4 on 2023-11-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0010_alter_estados_fin_ing_otr'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aso_benef',
            unique_together={('asociado', 'nombre')},
        ),
    ]
