# Generated by Django 4.2.4 on 2023-11-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0011_alter_aso_benef_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aso_benef',
            unique_together={('asociado', 'doc_ide')},
        ),
    ]
