# Generated by Django 5.0 on 2023-12-23 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0011_alter_imp_con_cre_int_cta_int_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='USUARIOS',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=16)),
                ('nit', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=44)),
                ('fec_ing', models.DateField(blank=True, null=True)),
                ('es_cajero', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('fec_sal', models.DateField(blank=True, null=True)),
                ('cta_con_acr', models.CharField(max_length=10)),
                ('activo', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('oficina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='justo_app.oficinas')),
            ],
            options={
                'db_table': 'usuarios',
                'unique_together': {('oficina', 'login')},
            },
        ),
    ]
