# Generated by Django 4.2.4 on 2024-01-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0011_remove_detalle_prod_detalle_pro_oficina_aca602_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cambios_cre',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cambios_cre',
            name='tip_cam',
            field=models.CharField(choices=[('2', 'Ajuste'), ('3', 'Des Pronto Pago'), ('4', 'Castigo/Condo')], max_length=1, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cambios_cre',
            unique_together={('det_pro', 'tip_cam')},
        ),
    ]
