# Generated by Django 5.0 on 2023-12-23 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0012_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cta_con_acr',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nit',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=44, null=True),
        ),
        migrations.CreateModel(
            name='cierre_mes',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True)),
                ('protegido', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('tot_deb', models.FloatField(blank=True)),
                ('tot_cre', models.FloatField(blank=True)),
                ('fec_cie', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.CharField(max_length=16)),
                ('oficina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='justo_app.oficinas')),
            ],
            options={
                'db_table': 'cierre_mes',
                'unique_together': {('oficina', 'fecha')},
            },
        ),
    ]
