# Generated by Django 4.2.4 on 2023-11-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0012_alter_aso_benef_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='aso_ref_fam',
            name='direccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aso_ref_fam',
            name='ocupacion',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
