# Generated by Django 4.2.4 on 2024-01-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0012_alter_cambios_cre_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambios_cre',
            name='des_pp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
