# Generated by Django 5.0 on 2023-12-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0013_alter_usuarios_cta_con_acr_alter_usuarios_nit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierre_mes',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
