# Generated by Django 4.2.4 on 2024-01-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0013_cambios_cre_des_pp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditos_causa',
            name='int_mor',
        ),
        migrations.RemoveField(
            model_name='creditos_causa',
            name='pol_seg',
        ),
        migrations.AddIndex(
            model_name='xmov_cre',
            index=models.Index(fields=['tip_mov'], name='xmov_cre_tip_mov_518647_idx'),
        ),
    ]
