# Generated by Django 4.2.4 on 2023-11-06 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0013_aso_ref_fam_direccion_aso_ref_fam_ocupacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORIGINACION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_sol', models.DateField()),
                ('lin_cre', models.CharField(max_length=30)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('plazo', models.IntegerField(blank=True, null=True)),
                ('gar_cre_sol', models.CharField(max_length=1)),
                ('lin_cre_sol', models.CharField(max_length=1)),
                ('mod_cre_sol', models.CharField(max_length=1)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justo_app.asociados')),
            ],
            options={
                'db_table': 'originacion',
                'unique_together': {('asociado', 'fec_sol')},
            },
        ),
    ]
