# Generated by Django 5.0 on 2023-12-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0014_alter_cierre_mes_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierre_mes',
            name='tot_cre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cierre_mes',
            name='tot_deb',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
