# Generated by Django 5.0 on 2023-12-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0015_alter_cierre_mes_tot_cre_alter_cierre_mes_tot_deb'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='cod_caj',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
