# Generated by Django 4.2.4 on 2023-11-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0015_alter_originacion_fec_sol'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='originacion',
            unique_together={('asociado',)},
        ),
        migrations.RemoveField(
            model_name='originacion',
            name='fec_sol',
        ),
    ]
