# Generated by Django 5.0 on 2023-12-24 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0016_usuarios_cod_caj'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOV_CAJA',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cod_caj', models.CharField(max_length=2)),
                ('jornada', models.CharField(max_length=1)),
                ('saldo_ini', models.FloatField(blank=True, null=True)),
                ('debitos', models.FloatField(blank=True, null=True)),
                ('creditos', models.FloatField(blank=True, null=True)),
                ('val_che_dev', models.FloatField(blank=True, null=True)),
                ('saldo_fin', models.FloatField(blank=True, null=True)),
                ('diferencia', models.FloatField(blank=True, null=True)),
                ('val_cheques', models.FloatField(blank=True, null=True)),
                ('val_vales', models.FloatField(blank=True, null=True)),
                ('cerrado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('monedas', models.JSONField(blank=True, null=True)),
                ('oficina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='justo_app.oficinas')),
            ],
            options={
                'db_table': 'mov_caja',
                'unique_together': {('oficina', 'fecha', 'cod_caj', 'jornada')},
            },
        ),
    ]
