# Generated by Django 5.0 on 2023-12-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0017_mov_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='docto_conta',
            name='codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docto_conta',
            name='nom_cto',
            field=models.CharField(max_length=12),
        ),
    ]
