# Generated by Django 4.2.4 on 2023-11-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0017_alter_asociados_oficina_alter_asociados_tercero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originacion',
            name='lin_cre',
            field=models.CharField(max_length=80),
        ),
    ]
