# Generated by Django 4.2.4 on 2023-11-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0018_alter_originacion_lin_cre'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociados',
            name='estado_anteia',
            field=models.CharField(choices=[('0', 'No Anteia'), ('1', 'Validar'), ('2', 'Por Validar'), ('3', 'Denegar')], default=2, max_length=1),
        ),
    ]
