# Generated by Django 5.0 on 2023-12-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0019_alter_docto_conta_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='docto_conta',
            name='doc_admin',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='docto_conta',
            name='doc_caja',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='docto_conta',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
