# Generated by Django 5.0 on 2023-12-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0020_docto_conta_doc_admin_docto_conta_doc_caja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docto_conta',
            name='nombre',
            field=models.CharField(max_length=44),
        ),
    ]
