# Generated by Django 5.0 on 2023-12-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0021_alter_docto_conta_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_ctas',
            name='tip_cta',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
