# Generated by Django 5.0 on 2023-12-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0022_plan_ctas_tip_cta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_ctas',
            name='auxiliar',
        ),
    ]
