# Generated by Django 5.0 on 2023-12-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0023_remove_plan_ctas_auxiliar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_ctas',
            name='nom_cta',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
