# Generated by Django 5.0 on 2023-12-24 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0024_alter_plan_ctas_nom_cta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONCEPTOS',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('cod_con', models.CharField(max_length=8)),
                ('con_justo', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('descripcion', models.CharField(max_length=44)),
                ('tip_dev_ap', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('tip_con', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('tip_sis', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('cta_con', models.CharField(max_length=10)),
                ('cta_con_pas', models.CharField(max_length=10)),
                ('debito', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('credito', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('por_tercero', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('por_ret_fue', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='justo_app.clientes')),
            ],
            options={
                'db_table': 'conceptos',
                'unique_together': {('cliente', 'cod_con')},
            },
        ),
    ]
