# Generated by Django 5.0 on 2023-12-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0025_conceptos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptos',
            name='por_ret_fue',
            field=models.FloatField(),
        ),
    ]
