# Generated by Django 5.0 on 2023-12-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0026_alter_conceptos_por_ret_fue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptos',
            name='por_ret_fue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
