# Generated by Django 5.0 on 2023-12-24 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0027_alter_conceptos_por_ret_fue'),
    ]

    operations = [
        migrations.CreateModel(
            name='LINEAS_CREDITO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_lin_cre', models.IntegerField()),
                ('descripcion', models.CharField(max_length=44, null=True)),
                ('tas_int_anu', models.FloatField()),
                ('tas_int_mor', models.FloatField()),
                ('por_pol', models.FloatField()),
                ('por_des_pp', models.FloatField()),
                ('dia_con_int_mor', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justo_app.clientes')),
            ],
            options={
                'db_table': 'lineas_credito',
                'unique_together': {('cliente', 'cod_lin_cre')},
            },
        ),
    ]
