# Generated by Django 5.0 on 2023-12-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0028_lineas_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineas_credito',
            name='dia_con_int_mor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lineas_credito',
            name='por_des_pp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='lineas_credito',
            name='por_pol',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='lineas_credito',
            name='tas_int_anu',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='lineas_credito',
            name='tas_int_mor',
            field=models.FloatField(null=True),
        ),
    ]
