# Generated by Django 5.0 on 2023-12-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0029_alter_lineas_credito_dia_con_int_mor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_econo',
            name='id_ds',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='docto_conta',
            name='id_ds',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hecho_econo',
            name='id_ds',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='plan_ctas',
            name='id_ds',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='terceros',
            name='id_ds',
            field=models.BigIntegerField(null=True),
        ),
    ]
