# Generated by Django 5.0 on 2023-12-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0030_detalle_econo_id_ds_docto_conta_id_ds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docto_conta',
            name='id_ds',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan_ctas',
            name='id_ds',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='id_ds',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
