# Generated by Django 5.0 on 2023-12-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0031_alter_docto_conta_id_ds_alter_plan_ctas_id_ds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hecho_econo',
            name='usuario',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
