# Generated by Django 5.0 on 2023-12-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0033_alter_detalle_econo_detalle_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_econo',
            name='credito',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='detalle_econo',
            name='debito',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='detalle_econo',
            name='detalle',
            field=models.TextField(null=True),
        ),
    ]
