# Generated by Django 5.0 on 2023-12-25 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0034_alter_detalle_econo_credito_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creditos',
            unique_together={('oficina', 'cod_cre')},
        ),
        migrations.AddField(
            model_name='creditos',
            name='socio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='justo_app.asociados'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='com_des',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='justo_app.hecho_econo'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='com_ult_cau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='justo_app.creditos_causa'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='imputacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='justo_app.imp_con_cre'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='num_cuo_act',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='num_cuo_gra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='num_cuo_ini',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='per_ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='por_des_pro_pag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='tian_ic_act',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='tian_ic_ini',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='tian_im',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='tian_pol_seg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='val_cuo_act',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='val_cuo_ini',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='val_gar_hip',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
