# Generated by Django 5.0 on 2023-12-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0035_alter_creditos_unique_together_creditos_socio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditos',
            name='fec_ult_pag',
            field=models.DateField(blank=True, null=True),
        ),
    ]
