# Generated by Django 5.0 on 2023-12-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0036_creditos_fec_ult_pag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditos',
            name='num_pol_gar_hip',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
