# Generated by Django 5.0 on 2023-12-25 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0038_alter_creditos_pagare'),
    ]

    operations = [
        migrations.CreateModel(
            name='CODEUDORES',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justo_app.creditos')),
                ('nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justo_app.terceros')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justo_app.oficinas')),
            ],
            options={
                'db_table': 'codeudores',
                'unique_together': {('oficina', 'credito', 'nit')},
            },
        ),
    ]
