# Generated by Django 5.0 on 2023-12-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0040_rename_nit_codeudores_tercero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XDOC_ZEP',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('per_con', models.IntegerField()),
                ('clase_zep', models.CharField(max_length=1)),
                ('doc_ds', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'xdoc_zep',
                'unique_together': {('per_con', 'clase_zep')},
            },
        ),
    ]
