# Generated by Django 5.0 on 2023-12-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0041_xdoc_zep'),
    ]

    operations = [
        migrations.AddField(
            model_name='xdoc_zep',
            name='descripcion',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name='xdoc_zep',
            name='nombre',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
