# Generated by Django 5.0 on 2023-12-26 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0042_xdoc_zep_descripcion_xdoc_zep_nombre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detalle_prod',
            unique_together={('hecho_econo', 'producto', 'concepto', 'subcuenta')},
        ),
        migrations.AlterField(
            model_name='detalle_prod',
            name='centro_costo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='justo_app.centrocostos'),
        ),
        migrations.AlterField(
            model_name='detalle_prod',
            name='valor',
            field=models.FloatField(null=True),
        ),
    ]
