# Generated by Django 4.2.4 on 2024-01-12 13:12

from django.db import migrations, models
import justo_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENTES',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=1)),
                ('doc_ide', models.CharField(help_text='el documento de identidad debe ser numérico.', max_length=12, null=True, validators=[justo_app.models.validate_numeric])),
                ('sigla', models.CharField(max_length=36)),
                ('nombre', models.CharField(max_length=120)),
                ('celular', models.CharField(help_text='El número de celular debe contener exactamente 10 dígitos numéricos.', max_length=10, null=True, validators=[justo_app.models.validate_numeric])),
                ('email', models.EmailField(max_length=254)),
                ('dominio', models.URLField()),
                ('dv', models.CharField(blank=True, max_length=1, null=True)),
                ('direccion', models.CharField(blank=True, max_length=128, null=True)),
                ('telefono', models.CharField(blank=True, help_text='El número de teléfono debe tener solo dígitos numéricos.', max_length=12, null=True, validators=[justo_app.models.validate_numeric])),
                ('nit_ger', models.CharField(blank=True, help_text='El número de documento debe ser numérico.', max_length=10, null=True, validators=[justo_app.models.validate_numeric])),
                ('nom_ger', models.CharField(blank=True, max_length=100, null=True)),
                ('nit_con', models.CharField(blank=True, help_text='El número de documento debe ser numérico.', max_length=10, null=True, validators=[justo_app.models.validate_numeric])),
                ('nom_con', models.CharField(blank=True, max_length=100, null=True)),
                ('age_ret', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('ret_iva', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('aut_ret', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('nit_rev_fis', models.CharField(blank=True, help_text='El número de documento debe ser numérico.', max_length=10, null=True, validators=[justo_app.models.validate_numeric])),
                ('nom_rev_fis', models.CharField(blank=True, max_length=100, null=True)),
                ('tp_con', models.CharField(blank=True, max_length=16, null=True)),
                ('tp_rev_fis', models.CharField(blank=True, max_length=16, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=32, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('numero_licencia', models.CharField(blank=True, max_length=8, null=True)),
                ('licencia_activa', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('inicio_licencia', models.DateField(blank=True, null=True)),
                ('fin_licencia', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'unique_together': {('codigo',)},
            },
        ),
    ]
