# Generated by Django 4.2.4 on 2024-01-12 13:51

from django.db import migrations, models
import justo_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='doc_ide',
            field=models.CharField(help_text='El documento de identidad debe ser numérico.', max_length=12, null=True, validators=[justo_app.models.validate_numeric]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='logo',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=''),
        ),
    ]
