# Generated by Django 4.2.4 on 2024-01-12 21:08

from django.db import migrations, models
import justo_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0004_alter_clientes_age_ret_alter_clientes_aut_ret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='doc_ide',
            field=models.CharField(help_text='El documento de identidad debe ser numérico.', max_length=12, validators=[justo_app.models.validate_numeric], verbose_name='Nit'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fin_lic',
            field=models.DateField(blank=True, verbose_name='Fecha Fin Licencia'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ini_lic',
            field=models.DateField(blank=True, verbose_name='Fecha Incio Licencia'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='num_lic',
            field=models.CharField(blank=True, max_length=8, verbose_name='Número Licencia'),
        ),
    ]
